version: '2'
services:
  agenda-app:
    image: agenda
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://agenda-mysql:3306/agenda?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  agenda-mysql:
    extends:
      file: mysql.yml
      service: agenda-mysql
